vars:
  token: {{ TOKEN }} # repo, admin:org
  owner: privateerproj

policy:
  catalogs:
    - OSPS_B
  applicability:
    - Maturity Level 1

write-directory: evaluation_results
services:
  privateer:
    plugin: github-repo
    vars:
      repo: privateer
  privateer-sdk:
    plugin: github-repo
    vars:
      repo: privateer-sdk

